---
title: "Mod 5 homework assignment"
author: Student Name
output: github_document
editor_options:
  chunk_output_type: inline
---

## EDA Mod 5: Data Report

Note: Be warned, it can take some time to choose a good data set! You might find yourself trying one and then realizing you need to switch to another. This is normal. This week's homework is worth 20 points instead of 10 in brightspace because I know it is a time consuming one.

# Part One
1. Choose a data set from: [This Google Spreadsheet](https://docs.google.com/spreadsheets/d/1B9ZwDU1gFsa9MLZaqg2EVk48tPIOc9qUZkf16t4xj4k/edit?usp=sharing)

2. Once you have chosen your data, add your name in the your_name column and appropriate row of your data as shown in the google spreadsheet. Once you've done this, no one else can use the data. If there is already a comment with someone's name, you cannot use it.

# Part Two

1. Write a paragraph of 4-5 sentences telling me about this data. 

- Who created this data, and why? 
- What was it used for? How would you describe the data generating process?
- What is the unit of analysis (what are the rows/observations)? 

2. Explore the data. What are the dimensions of the data? What types of variables are there? Use complete sentences to describe the data.

# Part Three

1. Center your analysis on an exploratory (or "motivating") question. Tell me what it is. Use complete sentences.

2. Explore your question using visualizations. 

- In the end, choose two 'final' plots to 'print' and interpret the visualization in 2-5 sentences. Do not show me tons of plots. Only include your final plots in your report. Create a separate file to show your work.
- Why did you choose these graphics? What do they show?

# Part Four

1. Answer the following questions, using complete sentences:

- how long did it take you to 'choose' this data?
- how much data wrangling, joining, subsetting, or other forms of data manipulation (such as variable creation, or relabeling) did you have to do? Why did you do it?
- what did you learn from your data exploration?

# Part Five

1. Save your 'write up' report in your homework repo. Knit to pdf file or github flavored markdown for easy online viewing.
2. You write up should include all of the answers to the above questions. *All of your work should be shown in your repository for this assignment*
3. Include your data file in your repository.
